//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MiniJavaGram.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class MiniJavaGramParser : Parser {
	public const int
		T__0=1, T__1=2, RETURN=3, CLASS=4, STATIC=5, DOUBLE=6, STRING=7, VOID=8, 
		ENUM=9, PUBLIC=10, FOR=11, DOUBLE_QUOTE=12, ARRAYSQARES=13, COMMETSLASH=14, 
		SYSTEMOUTPRINTLN=15, MULT=16, ASSIGN=17, OBRACE=18, CBRACE=19, DT=20, 
		DC=21, COMMA=22, DOT=23, LBRACKET=24, RBRACKET=25, PASS=26, DIGIT=27, 
		ID=28, WS=29;
	public const int
		RULE_prog = 0, RULE_classBody = 1, RULE_enumdeclar = 2, RULE_main = 3, 
		RULE_otherMthod = 4, RULE_args = 5, RULE_exprassion = 6, RULE_arraydeclaration = 7, 
		RULE_varible = 8, RULE_doubleVal = 9, RULE_doubleArr = 10, RULE_operator = 11, 
		RULE_string = 12, RULE_stringArgs = 13;
	public static readonly string[] ruleNames = {
		"prog", "classBody", "enumdeclar", "main", "otherMthod", "args", "exprassion", 
		"arraydeclaration", "varible", "doubleVal", "doubleArr", "operator", "string", 
		"stringArgs"
	};

	private static readonly string[] _LiteralNames = {
		null, "'main'", "' args'", "'return'", "'class'", "'static'", "'double'", 
		"'String'", "'void'", "'enum'", "'public'", "'for'", "'\"'", "'[]'", "'//'", 
		"'System.out.println'", "'*'", "'='", "'{'", "'}'", "':'", "';'", "','", 
		"'.'", "'('", "')'", "' '"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "RETURN", "CLASS", "STATIC", "DOUBLE", "STRING", "VOID", 
		"ENUM", "PUBLIC", "FOR", "DOUBLE_QUOTE", "ARRAYSQARES", "COMMETSLASH", 
		"SYSTEMOUTPRINTLN", "MULT", "ASSIGN", "OBRACE", "CBRACE", "DT", "DC", 
		"COMMA", "DOT", "LBRACKET", "RBRACKET", "PASS", "DIGIT", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MiniJavaGram.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public MiniJavaGramParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(MiniJavaGramParser.CLASS, 0); }
		public ITerminalNode ID() { return GetToken(MiniJavaGramParser.ID, 0); }
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ClassBodyContext classBody() {
			return GetRuleContext<ClassBodyContext>(0);
		}
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; Match(CLASS);
			State = 30;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 29; Match(PASS);
				}
				}
				State = 32;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 34; Match(ID);
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 35; Match(PASS);
				}
				}
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 40; Match(OBRACE);
			State = 41; classBody();
			State = 42; Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassBodyContext : ParserRuleContext {
		public ITerminalNode[] COMMETSLASH() { return GetTokens(MiniJavaGramParser.COMMETSLASH); }
		public ITerminalNode COMMETSLASH(int i) {
			return GetToken(MiniJavaGramParser.COMMETSLASH, i);
		}
		public OtherMthodContext[] otherMthod() {
			return GetRuleContexts<OtherMthodContext>();
		}
		public OtherMthodContext otherMthod(int i) {
			return GetRuleContext<OtherMthodContext>(i);
		}
		public EnumdeclarContext[] enumdeclar() {
			return GetRuleContexts<EnumdeclarContext>();
		}
		public EnumdeclarContext enumdeclar(int i) {
			return GetRuleContext<EnumdeclarContext>(i);
		}
		public MainContext main() {
			return GetRuleContext<MainContext>(0);
		}
		public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public ITerminalNode[] ID() { return GetTokens(MiniJavaGramParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(MiniJavaGramParser.ID, i);
		}
		public ClassBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterClassBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitClassBody(this);
		}
	}

	[RuleVersion(0)]
	public ClassBodyContext classBody() {
		ClassBodyContext _localctx = new ClassBodyContext(Context, State);
		EnterRule(_localctx, 2, RULE_classBody);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					State = 59;
					switch (TokenStream.La(1)) {
					case COMMETSLASH:
						{
						State = 44; Match(COMMETSLASH);
						State = 48;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
						while (_la==DOUBLE_QUOTE) {
							{
							{
							State = 45; @string();
							}
							}
							State = 50;
							ErrorHandler.Sync(this);
							_la = TokenStream.La(1);
						}
						State = 54;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
						while (_la==ID) {
							{
							{
							State = 51; Match(ID);
							}
							}
							State = 56;
							ErrorHandler.Sync(this);
							_la = TokenStream.La(1);
						}
						}
						break;
					case PUBLIC:
						{
						State = 57; otherMthod();
						}
						break;
					case ENUM:
						{
						State = 58; enumdeclar();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					} 
				}
				State = 63;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			State = 65;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 64; main();
				}
				break;
			}
			State = 84;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ENUM) | (1L << PUBLIC) | (1L << COMMETSLASH))) != 0)) {
				{
				State = 82;
				switch (TokenStream.La(1)) {
				case PUBLIC:
					{
					State = 67; otherMthod();
					}
					break;
				case ENUM:
					{
					State = 68; enumdeclar();
					}
					break;
				case COMMETSLASH:
					{
					State = 69; Match(COMMETSLASH);
					State = 73;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==DOUBLE_QUOTE) {
						{
						{
						State = 70; @string();
						}
						}
						State = 75;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					State = 79;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==ID) {
						{
						{
						State = 76; Match(ID);
						}
						}
						State = 81;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumdeclarContext : ParserRuleContext {
		public ITerminalNode ENUM() { return GetToken(MiniJavaGramParser.ENUM, 0); }
		public ITerminalNode[] ID() { return GetTokens(MiniJavaGramParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(MiniJavaGramParser.ID, i);
		}
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MiniJavaGramParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MiniJavaGramParser.COMMA, i);
		}
		public EnumdeclarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumdeclar; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterEnumdeclar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitEnumdeclar(this);
		}
	}

	[RuleVersion(0)]
	public EnumdeclarContext enumdeclar() {
		EnumdeclarContext _localctx = new EnumdeclarContext(Context, State);
		EnterRule(_localctx, 4, RULE_enumdeclar);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87; Match(ENUM);
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 88; Match(PASS);
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 93; Match(ID);
			State = 94; Match(OBRACE);
			State = 107;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==PASS || _la==ID) {
				{
				{
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 95; Match(PASS);
					}
					}
					State = 100;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 101; Match(ID);
				State = 103;
				_la = TokenStream.La(1);
				if (_la==COMMA) {
					{
					State = 102; Match(COMMA);
					}
				}

				}
				}
				State = 109;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 110; Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainContext : ParserRuleContext {
		public ITerminalNode PUBLIC() { return GetToken(MiniJavaGramParser.PUBLIC, 0); }
		public ITerminalNode STATIC() { return GetToken(MiniJavaGramParser.STATIC, 0); }
		public ITerminalNode VOID() { return GetToken(MiniJavaGramParser.VOID, 0); }
		public ITerminalNode LBRACKET() { return GetToken(MiniJavaGramParser.LBRACKET, 0); }
		public StringArgsContext stringArgs() {
			return GetRuleContext<StringArgsContext>(0);
		}
		public ITerminalNode RBRACKET() { return GetToken(MiniJavaGramParser.RBRACKET, 0); }
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ExprassionContext[] exprassion() {
			return GetRuleContexts<ExprassionContext>();
		}
		public ExprassionContext exprassion(int i) {
			return GetRuleContext<ExprassionContext>(i);
		}
		public MainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_main; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterMain(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitMain(this);
		}
	}

	[RuleVersion(0)]
	public MainContext main() {
		MainContext _localctx = new MainContext(Context, State);
		EnterRule(_localctx, 6, RULE_main);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(PUBLIC);
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 113; Match(PASS);
				}
				}
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 118; Match(STATIC);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 119; Match(PASS);
				}
				}
				State = 122;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 124; Match(VOID);
			State = 126;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 125; Match(PASS);
				}
				}
				State = 128;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 130; Match(T__0);
			State = 131; Match(LBRACKET);
			State = 132; stringArgs();
			State = 133; Match(RBRACKET);
			State = 135;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 134; Match(PASS);
				}
				}
				State = 137;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 139; Match(OBRACE);
			State = 143;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << DOUBLE) | (1L << FOR) | (1L << COMMETSLASH) | (1L << SYSTEMOUTPRINTLN) | (1L << ID))) != 0)) {
				{
				{
				State = 140; exprassion();
				}
				}
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 146; Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OtherMthodContext : ParserRuleContext {
		public ITerminalNode PUBLIC() { return GetToken(MiniJavaGramParser.PUBLIC, 0); }
		public ITerminalNode STATIC() { return GetToken(MiniJavaGramParser.STATIC, 0); }
		public ITerminalNode ID() { return GetToken(MiniJavaGramParser.ID, 0); }
		public ITerminalNode LBRACKET() { return GetToken(MiniJavaGramParser.LBRACKET, 0); }
		public ArgsContext args() {
			return GetRuleContext<ArgsContext>(0);
		}
		public ITerminalNode RBRACKET() { return GetToken(MiniJavaGramParser.RBRACKET, 0); }
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public ITerminalNode DOUBLE() { return GetToken(MiniJavaGramParser.DOUBLE, 0); }
		public ITerminalNode VOID() { return GetToken(MiniJavaGramParser.VOID, 0); }
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ExprassionContext[] exprassion() {
			return GetRuleContexts<ExprassionContext>();
		}
		public ExprassionContext exprassion(int i) {
			return GetRuleContext<ExprassionContext>(i);
		}
		public OtherMthodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_otherMthod; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterOtherMthod(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitOtherMthod(this);
		}
	}

	[RuleVersion(0)]
	public OtherMthodContext otherMthod() {
		OtherMthodContext _localctx = new OtherMthodContext(Context, State);
		EnterRule(_localctx, 8, RULE_otherMthod);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148; Match(PUBLIC);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 149; Match(PASS);
				}
				}
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 154; Match(STATIC);
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 155; Match(PASS);
				}
				}
				State = 158;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 160;
			_la = TokenStream.La(1);
			if ( !(_la==DOUBLE || _la==VOID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
			    Consume();
			}
			State = 162;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 161; Match(PASS);
				}
				}
				State = 164;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 166; Match(ID);
			State = 167; Match(LBRACKET);
			State = 168; args();
			State = 169; Match(RBRACKET);
			State = 170; Match(OBRACE);
			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << DOUBLE) | (1L << FOR) | (1L << COMMETSLASH) | (1L << SYSTEMOUTPRINTLN) | (1L << ID))) != 0)) {
				{
				{
				State = 171; exprassion();
				}
				}
				State = 176;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 177; Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgsContext : ParserRuleContext {
		public ITerminalNode[] DOUBLE() { return GetTokens(MiniJavaGramParser.DOUBLE); }
		public ITerminalNode DOUBLE(int i) {
			return GetToken(MiniJavaGramParser.DOUBLE, i);
		}
		public ITerminalNode[] ID() { return GetTokens(MiniJavaGramParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(MiniJavaGramParser.ID, i);
		}
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MiniJavaGramParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MiniJavaGramParser.COMMA, i);
		}
		public ArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_args; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterArgs(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitArgs(this);
		}
	}

	[RuleVersion(0)]
	public ArgsContext args() {
		ArgsContext _localctx = new ArgsContext(Context, State);
		EnterRule(_localctx, 10, RULE_args);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==DOUBLE) {
				{
				{
				State = 179; Match(DOUBLE);
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 180; Match(PASS);
					}
					}
					State = 183;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 185; Match(ID);
				State = 189;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 186; Match(PASS);
					}
					}
					State = 191;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 193;
				_la = TokenStream.La(1);
				if (_la==COMMA) {
					{
					State = 192; Match(COMMA);
					}
				}

				}
				}
				State = 199;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprassionContext : ParserRuleContext {
		public ITerminalNode RETURN() { return GetToken(MiniJavaGramParser.RETURN, 0); }
		public VaribleContext[] varible() {
			return GetRuleContexts<VaribleContext>();
		}
		public VaribleContext varible(int i) {
			return GetRuleContext<VaribleContext>(i);
		}
		public OperatorContext @operator() {
			return GetRuleContext<OperatorContext>(0);
		}
		public ITerminalNode DC() { return GetToken(MiniJavaGramParser.DC, 0); }
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ITerminalNode SYSTEMOUTPRINTLN() { return GetToken(MiniJavaGramParser.SYSTEMOUTPRINTLN, 0); }
		public ITerminalNode[] LBRACKET() { return GetTokens(MiniJavaGramParser.LBRACKET); }
		public ITerminalNode LBRACKET(int i) {
			return GetToken(MiniJavaGramParser.LBRACKET, i);
		}
		public ITerminalNode[] RBRACKET() { return GetTokens(MiniJavaGramParser.RBRACKET); }
		public ITerminalNode RBRACKET(int i) {
			return GetToken(MiniJavaGramParser.RBRACKET, i);
		}
		public ITerminalNode[] ID() { return GetTokens(MiniJavaGramParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(MiniJavaGramParser.ID, i);
		}
		public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public ITerminalNode DOT() { return GetToken(MiniJavaGramParser.DOT, 0); }
		public ArraydeclarationContext arraydeclaration() {
			return GetRuleContext<ArraydeclarationContext>(0);
		}
		public ITerminalNode FOR() { return GetToken(MiniJavaGramParser.FOR, 0); }
		public ITerminalNode DOUBLE() { return GetToken(MiniJavaGramParser.DOUBLE, 0); }
		public ITerminalNode DT() { return GetToken(MiniJavaGramParser.DT, 0); }
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public ExprassionContext[] exprassion() {
			return GetRuleContexts<ExprassionContext>();
		}
		public ExprassionContext exprassion(int i) {
			return GetRuleContext<ExprassionContext>(i);
		}
		public ITerminalNode COMMETSLASH() { return GetToken(MiniJavaGramParser.COMMETSLASH, 0); }
		public ITerminalNode ASSIGN() { return GetToken(MiniJavaGramParser.ASSIGN, 0); }
		public DoubleValContext[] doubleVal() {
			return GetRuleContexts<DoubleValContext>();
		}
		public DoubleValContext doubleVal(int i) {
			return GetRuleContext<DoubleValContext>(i);
		}
		public ITerminalNode MULT() { return GetToken(MiniJavaGramParser.MULT, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(MiniJavaGramParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MiniJavaGramParser.COMMA, i);
		}
		public ExprassionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprassion; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterExprassion(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitExprassion(this);
		}
	}

	[RuleVersion(0)]
	public ExprassionContext exprassion() {
		ExprassionContext _localctx = new ExprassionContext(Context, State);
		EnterRule(_localctx, 12, RULE_exprassion);
		int _la;
		try {
			int _alt;
			State = 376;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,53,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 200; Match(RETURN);
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 201; Match(PASS);
					}
					}
					State = 204;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 206; varible();
				State = 210;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 207; Match(PASS);
					}
					}
					State = 212;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 213; @operator();
				State = 217;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 214; Match(PASS);
					}
					}
					State = 219;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 220; varible();
				State = 221; Match(DC);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 223; Match(SYSTEMOUTPRINTLN);
				State = 224; Match(LBRACKET);
				State = 234;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
				case 1:
					{
					State = 225; Match(ID);
					State = 226; Match(LBRACKET);
					State = 227; Match(ID);
					State = 228; Match(RBRACKET);
					}
					break;
				case 2:
					{
					State = 229; Match(ID);
					}
					break;
				case 3:
					{
					State = 230; @string();
					}
					break;
				case 4:
					{
					State = 231; Match(ID);
					State = 232; Match(DOT);
					State = 233; Match(ID);
					}
					break;
				}
				State = 236; Match(RBRACKET);
				State = 237; Match(DC);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 238; arraydeclaration();
				State = 239; Match(DC);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 241; Match(FOR);
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 242; Match(PASS);
					}
					}
					State = 245;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 247; Match(LBRACKET);
				State = 248; Match(DOUBLE);
				State = 250;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 249; Match(PASS);
					}
					}
					State = 252;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 254; Match(ID);
				State = 255; Match(DT);
				State = 257;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 256; Match(PASS);
					}
					}
					State = 259;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 261; Match(ID);
				State = 262; Match(RBRACKET);
				State = 263; Match(OBRACE);
				State = 267;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << DOUBLE) | (1L << FOR) | (1L << COMMETSLASH) | (1L << SYSTEMOUTPRINTLN) | (1L << ID))) != 0)) {
					{
					{
					State = 264; exprassion();
					}
					}
					State = 269;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 270; Match(CBRACE);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 271; Match(COMMETSLASH);
				State = 275;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==DOUBLE_QUOTE) {
					{
					{
					State = 272; @string();
					}
					}
					State = 277;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 281;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,37,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 278; Match(ID);
						}
						} 
					}
					State = 283;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,37,Context);
				}
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 284; Match(DOUBLE);
				State = 286;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 285; Match(PASS);
					}
					}
					State = 288;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==PASS );
				State = 290; Match(ID);
				State = 294;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 291; Match(PASS);
					}
					}
					State = 296;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 297; Match(ASSIGN);
				State = 301;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 298; Match(PASS);
					}
					}
					State = 303;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 304; doubleVal();
				State = 308;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 305; Match(PASS);
					}
					}
					State = 310;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 311; Match(DC);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 319;
				_la = TokenStream.La(1);
				if (_la==DOUBLE) {
					{
					State = 313; Match(DOUBLE);
					State = 315;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					do {
						{
						{
						State = 314; Match(PASS);
						}
						}
						State = 317;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					} while ( _la==PASS );
					}
				}

				State = 321; Match(ID);
				State = 325;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 322; Match(PASS);
					}
					}
					State = 327;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 328; Match(ASSIGN);
				State = 332;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 329; Match(PASS);
					}
					}
					State = 334;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 337;
				switch (TokenStream.La(1)) {
				case ID:
					{
					State = 335; Match(ID);
					}
					break;
				case DIGIT:
					{
					State = 336; doubleVal();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 342;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 339; Match(PASS);
					}
					}
					State = 344;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 345; Match(MULT);
				State = 349;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 346; Match(PASS);
					}
					}
					State = 351;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 354;
				switch (TokenStream.La(1)) {
				case ID:
					{
					State = 352; Match(ID);
					}
					break;
				case DIGIT:
					{
					State = 353; doubleVal();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 359;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==PASS) {
					{
					{
					State = 356; Match(PASS);
					}
					}
					State = 361;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 362; Match(DC);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 363; Match(ID);
				State = 364; Match(LBRACKET);
				State = 371;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==ID) {
					{
					{
					State = 365; Match(ID);
					State = 367;
					_la = TokenStream.La(1);
					if (_la==COMMA) {
						{
						State = 366; Match(COMMA);
						}
					}

					}
					}
					State = 373;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 374; Match(RBRACKET);
				State = 375; Match(DC);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArraydeclarationContext : ParserRuleContext {
		public ITerminalNode DOUBLE() { return GetToken(MiniJavaGramParser.DOUBLE, 0); }
		public ITerminalNode ARRAYSQARES() { return GetToken(MiniJavaGramParser.ARRAYSQARES, 0); }
		public ITerminalNode ID() { return GetToken(MiniJavaGramParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(MiniJavaGramParser.ASSIGN, 0); }
		public DoubleArrContext doubleArr() {
			return GetRuleContext<DoubleArrContext>(0);
		}
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ArraydeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arraydeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterArraydeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitArraydeclaration(this);
		}
	}

	[RuleVersion(0)]
	public ArraydeclarationContext arraydeclaration() {
		ArraydeclarationContext _localctx = new ArraydeclarationContext(Context, State);
		EnterRule(_localctx, 14, RULE_arraydeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 378; Match(DOUBLE);
			State = 379; Match(ARRAYSQARES);
			State = 381;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			do {
				{
				{
				State = 380; Match(PASS);
				}
				}
				State = 383;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			} while ( _la==PASS );
			State = 385; Match(ID);
			State = 389;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==PASS) {
				{
				{
				State = 386; Match(PASS);
				}
				}
				State = 391;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 392; Match(ASSIGN);
			State = 396;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==PASS) {
				{
				{
				State = 393; Match(PASS);
				}
				}
				State = 398;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 399; doubleArr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VaribleContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(MiniJavaGramParser.ID, 0); }
		public DoubleValContext doubleVal() {
			return GetRuleContext<DoubleValContext>(0);
		}
		public VaribleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varible; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterVarible(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitVarible(this);
		}
	}

	[RuleVersion(0)]
	public VaribleContext varible() {
		VaribleContext _localctx = new VaribleContext(Context, State);
		EnterRule(_localctx, 16, RULE_varible);
		try {
			State = 403;
			switch (TokenStream.La(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 401; Match(ID);
				}
				break;
			case DIGIT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 402; doubleVal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DoubleValContext : ParserRuleContext {
		public ITerminalNode[] DIGIT() { return GetTokens(MiniJavaGramParser.DIGIT); }
		public ITerminalNode DIGIT(int i) {
			return GetToken(MiniJavaGramParser.DIGIT, i);
		}
		public ITerminalNode DOT() { return GetToken(MiniJavaGramParser.DOT, 0); }
		public DoubleValContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_doubleVal; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterDoubleVal(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitDoubleVal(this);
		}
	}

	[RuleVersion(0)]
	public DoubleValContext doubleVal() {
		DoubleValContext _localctx = new DoubleValContext(Context, State);
		EnterRule(_localctx, 18, RULE_doubleVal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 405; Match(DIGIT);
			State = 406; Match(DOT);
			State = 407; Match(DIGIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DoubleArrContext : ParserRuleContext {
		public ITerminalNode OBRACE() { return GetToken(MiniJavaGramParser.OBRACE, 0); }
		public ITerminalNode CBRACE() { return GetToken(MiniJavaGramParser.CBRACE, 0); }
		public DoubleValContext[] doubleVal() {
			return GetRuleContexts<DoubleValContext>();
		}
		public DoubleValContext doubleVal(int i) {
			return GetRuleContext<DoubleValContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MiniJavaGramParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MiniJavaGramParser.COMMA, i);
		}
		public DoubleArrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_doubleArr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterDoubleArr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitDoubleArr(this);
		}
	}

	[RuleVersion(0)]
	public DoubleArrContext doubleArr() {
		DoubleArrContext _localctx = new DoubleArrContext(Context, State);
		EnterRule(_localctx, 20, RULE_doubleArr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 409; Match(OBRACE);
			State = 416;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==DIGIT) {
				{
				{
				State = 410; doubleVal();
				State = 412;
				_la = TokenStream.La(1);
				if (_la==COMMA) {
					{
					State = 411; Match(COMMA);
					}
				}

				}
				}
				State = 418;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 419; Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorContext : ParserRuleContext {
		public ITerminalNode ASSIGN() { return GetToken(MiniJavaGramParser.ASSIGN, 0); }
		public ITerminalNode MULT() { return GetToken(MiniJavaGramParser.MULT, 0); }
		public OperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
	}

	[RuleVersion(0)]
	public OperatorContext @operator() {
		OperatorContext _localctx = new OperatorContext(Context, State);
		EnterRule(_localctx, 22, RULE_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 421;
			_la = TokenStream.La(1);
			if ( !(_la==MULT || _la==ASSIGN) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		public ITerminalNode[] DOUBLE_QUOTE() { return GetTokens(MiniJavaGramParser.DOUBLE_QUOTE); }
		public ITerminalNode DOUBLE_QUOTE(int i) {
			return GetToken(MiniJavaGramParser.DOUBLE_QUOTE, i);
		}
		public ITerminalNode[] ID() { return GetTokens(MiniJavaGramParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(MiniJavaGramParser.ID, i);
		}
		public ITerminalNode[] PASS() { return GetTokens(MiniJavaGramParser.PASS); }
		public ITerminalNode PASS(int i) {
			return GetToken(MiniJavaGramParser.PASS, i);
		}
		public ITerminalNode[] DOT() { return GetTokens(MiniJavaGramParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(MiniJavaGramParser.DOT, i);
		}
		public ITerminalNode[] DT() { return GetTokens(MiniJavaGramParser.DT); }
		public ITerminalNode DT(int i) {
			return GetToken(MiniJavaGramParser.DT, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MiniJavaGramParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MiniJavaGramParser.COMMA, i);
		}
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterString(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitString(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 24, RULE_string);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 423; Match(DOUBLE_QUOTE);
			State = 464;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==ID) {
				{
				State = 462;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,66,Context) ) {
				case 1:
					{
					State = 424; Match(ID);
					State = 428;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,60,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
						if ( _alt==1 ) {
							{
							{
							State = 425; Match(PASS);
							}
							} 
						}
						State = 430;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,60,Context);
					}
					State = 434;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==DOT) {
						{
						{
						State = 431; Match(DOT);
						}
						}
						State = 436;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					State = 440;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==DT) {
						{
						{
						State = 437; Match(DT);
						}
						}
						State = 442;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					State = 446;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==COMMA) {
						{
						{
						State = 443; Match(COMMA);
						}
						}
						State = 448;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					State = 452;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==PASS) {
						{
						{
						State = 449; Match(PASS);
						}
						}
						State = 454;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					}
					break;
				case 2:
					{
					State = 455; Match(ID);
					State = 459;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
					while (_la==DOT) {
						{
						{
						State = 456; Match(DOT);
						}
						}
						State = 461;
						ErrorHandler.Sync(this);
						_la = TokenStream.La(1);
					}
					}
					break;
				}
				}
				State = 466;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 467; Match(DOUBLE_QUOTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringArgsContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(MiniJavaGramParser.STRING, 0); }
		public ITerminalNode ARRAYSQARES() { return GetToken(MiniJavaGramParser.ARRAYSQARES, 0); }
		public StringArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringArgs; } }
		public override void EnterRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.EnterStringArgs(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IMiniJavaGramListener typedListener = listener as IMiniJavaGramListener;
			if (typedListener != null) typedListener.ExitStringArgs(this);
		}
	}

	[RuleVersion(0)]
	public StringArgsContext stringArgs() {
		StringArgsContext _localctx = new StringArgsContext(Context, State);
		EnterRule(_localctx, 26, RULE_stringArgs);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 469; Match(STRING);
			State = 470; Match(ARRAYSQARES);
			State = 471; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x1F");
		sb.Append("\x1DC\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6");
		sb.Append("\x4\a\t\a\x4\b\t\b\x4\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r");
		sb.Append("\t\r\x4\xE\t\xE\x4\xF\t\xF\x3\x2\x3\x2\x6\x2!\n\x2\r\x2\xE\x2");
		sb.Append("\"\x3\x2\x3\x2\x6\x2\'\n\x2\r\x2\xE\x2(\x3\x2\x3\x2\x3\x2\x3");
		sb.Append("\x2\x3\x3\x3\x3\a\x3\x31\n\x3\f\x3\xE\x3\x34\v\x3\x3\x3\a\x3");
		sb.Append("\x37\n\x3\f\x3\xE\x3:\v\x3\x3\x3\x3\x3\a\x3>\n\x3\f\x3\xE\x3");
		sb.Append("\x41\v\x3\x3\x3\x5\x3\x44\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3");
		sb.Append("J\n\x3\f\x3\xE\x3M\v\x3\x3\x3\a\x3P\n\x3\f\x3\xE\x3S\v\x3\a");
		sb.Append("\x3U\n\x3\f\x3\xE\x3X\v\x3\x3\x4\x3\x4\x6\x4\\\n\x4\r\x4\xE");
		sb.Append("\x4]\x3\x4\x3\x4\x3\x4\a\x4\x63\n\x4\f\x4\xE\x4\x66\v\x4\x3");
		sb.Append("\x4\x3\x4\x5\x4j\n\x4\a\x4l\n\x4\f\x4\xE\x4o\v\x4\x3\x4\x3\x4");
		sb.Append("\x3\x5\x3\x5\x6\x5u\n\x5\r\x5\xE\x5v\x3\x5\x3\x5\x6\x5{\n\x5");
		sb.Append("\r\x5\xE\x5|\x3\x5\x3\x5\x6\x5\x81\n\x5\r\x5\xE\x5\x82\x3\x5");
		sb.Append("\x3\x5\x3\x5\x3\x5\x3\x5\x6\x5\x8A\n\x5\r\x5\xE\x5\x8B\x3\x5");
		sb.Append("\x3\x5\a\x5\x90\n\x5\f\x5\xE\x5\x93\v\x5\x3\x5\x3\x5\x3\x6\x3");
		sb.Append("\x6\x6\x6\x99\n\x6\r\x6\xE\x6\x9A\x3\x6\x3\x6\x6\x6\x9F\n\x6");
		sb.Append("\r\x6\xE\x6\xA0\x3\x6\x3\x6\x6\x6\xA5\n\x6\r\x6\xE\x6\xA6\x3");
		sb.Append("\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\a\x6\xAF\n\x6\f\x6\xE\x6\xB2");
		sb.Append("\v\x6\x3\x6\x3\x6\x3\a\x3\a\x6\a\xB8\n\a\r\a\xE\a\xB9\x3\a\x3");
		sb.Append("\a\a\a\xBE\n\a\f\a\xE\a\xC1\v\a\x3\a\x5\a\xC4\n\a\a\a\xC6\n");
		sb.Append("\a\f\a\xE\a\xC9\v\a\x3\b\x3\b\x6\b\xCD\n\b\r\b\xE\b\xCE\x3\b");
		sb.Append("\x3\b\a\b\xD3\n\b\f\b\xE\b\xD6\v\b\x3\b\x3\b\a\b\xDA\n\b\f\b");
		sb.Append("\xE\b\xDD\v\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3");
		sb.Append("\b\x3\b\x3\b\x3\b\x3\b\x5\b\xED\n\b\x3\b\x3\b\x3\b\x3\b\x3\b");
		sb.Append("\x3\b\x3\b\x6\b\xF6\n\b\r\b\xE\b\xF7\x3\b\x3\b\x3\b\x6\b\xFD");
		sb.Append("\n\b\r\b\xE\b\xFE\x3\b\x3\b\x3\b\x6\b\x104\n\b\r\b\xE\b\x105");
		sb.Append("\x3\b\x3\b\x3\b\x3\b\a\b\x10C\n\b\f\b\xE\b\x10F\v\b\x3\b\x3");
		sb.Append("\b\x3\b\a\b\x114\n\b\f\b\xE\b\x117\v\b\x3\b\a\b\x11A\n\b\f\b");
		sb.Append("\xE\b\x11D\v\b\x3\b\x3\b\x6\b\x121\n\b\r\b\xE\b\x122\x3\b\x3");
		sb.Append("\b\a\b\x127\n\b\f\b\xE\b\x12A\v\b\x3\b\x3\b\a\b\x12E\n\b\f\b");
		sb.Append("\xE\b\x131\v\b\x3\b\x3\b\a\b\x135\n\b\f\b\xE\b\x138\v\b\x3\b");
		sb.Append("\x3\b\x3\b\x3\b\x6\b\x13E\n\b\r\b\xE\b\x13F\x5\b\x142\n\b\x3");
		sb.Append("\b\x3\b\a\b\x146\n\b\f\b\xE\b\x149\v\b\x3\b\x3\b\a\b\x14D\n");
		sb.Append("\b\f\b\xE\b\x150\v\b\x3\b\x3\b\x5\b\x154\n\b\x3\b\a\b\x157\n");
		sb.Append("\b\f\b\xE\b\x15A\v\b\x3\b\x3\b\a\b\x15E\n\b\f\b\xE\b\x161\v");
		sb.Append("\b\x3\b\x3\b\x5\b\x165\n\b\x3\b\a\b\x168\n\b\f\b\xE\b\x16B\v");
		sb.Append("\b\x3\b\x3\b\x3\b\x3\b\x3\b\x5\b\x172\n\b\a\b\x174\n\b\f\b\xE");
		sb.Append("\b\x177\v\b\x3\b\x3\b\x5\b\x17B\n\b\x3\t\x3\t\x3\t\x6\t\x180");
		sb.Append("\n\t\r\t\xE\t\x181\x3\t\x3\t\a\t\x186\n\t\f\t\xE\t\x189\v\t");
		sb.Append("\x3\t\x3\t\a\t\x18D\n\t\f\t\xE\t\x190\v\t\x3\t\x3\t\x3\n\x3");
		sb.Append("\n\x5\n\x196\n\n\x3\v\x3\v\x3\v\x3\v\x3\f\x3\f\x3\f\x5\f\x19F");
		sb.Append("\n\f\a\f\x1A1\n\f\f\f\xE\f\x1A4\v\f\x3\f\x3\f\x3\r\x3\r\x3\xE");
		sb.Append("\x3\xE\x3\xE\a\xE\x1AD\n\xE\f\xE\xE\xE\x1B0\v\xE\x3\xE\a\xE");
		sb.Append("\x1B3\n\xE\f\xE\xE\xE\x1B6\v\xE\x3\xE\a\xE\x1B9\n\xE\f\xE\xE");
		sb.Append("\xE\x1BC\v\xE\x3\xE\a\xE\x1BF\n\xE\f\xE\xE\xE\x1C2\v\xE\x3\xE");
		sb.Append("\a\xE\x1C5\n\xE\f\xE\xE\xE\x1C8\v\xE\x3\xE\x3\xE\a\xE\x1CC\n");
		sb.Append("\xE\f\xE\xE\xE\x1CF\v\xE\a\xE\x1D1\n\xE\f\xE\xE\xE\x1D4\v\xE");
		sb.Append("\x3\xE\x3\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x2\x2\x10\x2\x4\x6");
		sb.Append("\b\n\f\xE\x10\x12\x14\x16\x18\x1A\x1C\x2\x4\x4\x2\b\b\n\n\x3");
		sb.Append("\x2\x12\x13\x21B\x2\x1E\x3\x2\x2\x2\x4?\x3\x2\x2\x2\x6Y\x3\x2");
		sb.Append("\x2\x2\br\x3\x2\x2\x2\n\x96\x3\x2\x2\x2\f\xC7\x3\x2\x2\x2\xE");
		sb.Append("\x17A\x3\x2\x2\x2\x10\x17C\x3\x2\x2\x2\x12\x195\x3\x2\x2\x2");
		sb.Append("\x14\x197\x3\x2\x2\x2\x16\x19B\x3\x2\x2\x2\x18\x1A7\x3\x2\x2");
		sb.Append("\x2\x1A\x1A9\x3\x2\x2\x2\x1C\x1D7\x3\x2\x2\x2\x1E \a\x6\x2\x2");
		sb.Append("\x1F!\a\x1C\x2\x2 \x1F\x3\x2\x2\x2!\"\x3\x2\x2\x2\" \x3\x2\x2");
		sb.Append("\x2\"#\x3\x2\x2\x2#$\x3\x2\x2\x2$&\a\x1E\x2\x2%\'\a\x1C\x2\x2");
		sb.Append("&%\x3\x2\x2\x2\'(\x3\x2\x2\x2(&\x3\x2\x2\x2()\x3\x2\x2\x2)*");
		sb.Append("\x3\x2\x2\x2*+\a\x14\x2\x2+,\x5\x4\x3\x2,-\a\x15\x2\x2-\x3\x3");
		sb.Append("\x2\x2\x2.\x32\a\x10\x2\x2/\x31\x5\x1A\xE\x2\x30/\x3\x2\x2\x2");
		sb.Append("\x31\x34\x3\x2\x2\x2\x32\x30\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2");
		sb.Append("\x33\x38\x3\x2\x2\x2\x34\x32\x3\x2\x2\x2\x35\x37\a\x1E\x2\x2");
		sb.Append("\x36\x35\x3\x2\x2\x2\x37:\x3\x2\x2\x2\x38\x36\x3\x2\x2\x2\x38");
		sb.Append("\x39\x3\x2\x2\x2\x39>\x3\x2\x2\x2:\x38\x3\x2\x2\x2;>\x5\n\x6");
		sb.Append("\x2<>\x5\x6\x4\x2=.\x3\x2\x2\x2=;\x3\x2\x2\x2=<\x3\x2\x2\x2");
		sb.Append(">\x41\x3\x2\x2\x2?=\x3\x2\x2\x2?@\x3\x2\x2\x2@\x43\x3\x2\x2");
		sb.Append("\x2\x41?\x3\x2\x2\x2\x42\x44\x5\b\x5\x2\x43\x42\x3\x2\x2\x2");
		sb.Append("\x43\x44\x3\x2\x2\x2\x44V\x3\x2\x2\x2\x45U\x5\n\x6\x2\x46U\x5");
		sb.Append("\x6\x4\x2GK\a\x10\x2\x2HJ\x5\x1A\xE\x2IH\x3\x2\x2\x2JM\x3\x2");
		sb.Append("\x2\x2KI\x3\x2\x2\x2KL\x3\x2\x2\x2LQ\x3\x2\x2\x2MK\x3\x2\x2");
		sb.Append("\x2NP\a\x1E\x2\x2ON\x3\x2\x2\x2PS\x3\x2\x2\x2QO\x3\x2\x2\x2");
		sb.Append("QR\x3\x2\x2\x2RU\x3\x2\x2\x2SQ\x3\x2\x2\x2T\x45\x3\x2\x2\x2");
		sb.Append("T\x46\x3\x2\x2\x2TG\x3\x2\x2\x2UX\x3\x2\x2\x2VT\x3\x2\x2\x2");
		sb.Append("VW\x3\x2\x2\x2W\x5\x3\x2\x2\x2XV\x3\x2\x2\x2Y[\a\v\x2\x2Z\\");
		sb.Append("\a\x1C\x2\x2[Z\x3\x2\x2\x2\\]\x3\x2\x2\x2][\x3\x2\x2\x2]^\x3");
		sb.Append("\x2\x2\x2^_\x3\x2\x2\x2_`\a\x1E\x2\x2`m\a\x14\x2\x2\x61\x63");
		sb.Append("\a\x1C\x2\x2\x62\x61\x3\x2\x2\x2\x63\x66\x3\x2\x2\x2\x64\x62");
		sb.Append("\x3\x2\x2\x2\x64\x65\x3\x2\x2\x2\x65g\x3\x2\x2\x2\x66\x64\x3");
		sb.Append("\x2\x2\x2gi\a\x1E\x2\x2hj\a\x18\x2\x2ih\x3\x2\x2\x2ij\x3\x2");
		sb.Append("\x2\x2jl\x3\x2\x2\x2k\x64\x3\x2\x2\x2lo\x3\x2\x2\x2mk\x3\x2");
		sb.Append("\x2\x2mn\x3\x2\x2\x2np\x3\x2\x2\x2om\x3\x2\x2\x2pq\a\x15\x2");
		sb.Append("\x2q\a\x3\x2\x2\x2rt\a\f\x2\x2su\a\x1C\x2\x2ts\x3\x2\x2\x2u");
		sb.Append("v\x3\x2\x2\x2vt\x3\x2\x2\x2vw\x3\x2\x2\x2wx\x3\x2\x2\x2xz\a");
		sb.Append("\a\x2\x2y{\a\x1C\x2\x2zy\x3\x2\x2\x2{|\x3\x2\x2\x2|z\x3\x2\x2");
		sb.Append("\x2|}\x3\x2\x2\x2}~\x3\x2\x2\x2~\x80\a\n\x2\x2\x7F\x81\a\x1C");
		sb.Append("\x2\x2\x80\x7F\x3\x2\x2\x2\x81\x82\x3\x2\x2\x2\x82\x80\x3\x2");
		sb.Append("\x2\x2\x82\x83\x3\x2\x2\x2\x83\x84\x3\x2\x2\x2\x84\x85\a\x3");
		sb.Append("\x2\x2\x85\x86\a\x1A\x2\x2\x86\x87\x5\x1C\xF\x2\x87\x89\a\x1B");
		sb.Append("\x2\x2\x88\x8A\a\x1C\x2\x2\x89\x88\x3\x2\x2\x2\x8A\x8B\x3\x2");
		sb.Append("\x2\x2\x8B\x89\x3\x2\x2\x2\x8B\x8C\x3\x2\x2\x2\x8C\x8D\x3\x2");
		sb.Append("\x2\x2\x8D\x91\a\x14\x2\x2\x8E\x90\x5\xE\b\x2\x8F\x8E\x3\x2");
		sb.Append("\x2\x2\x90\x93\x3\x2\x2\x2\x91\x8F\x3\x2\x2\x2\x91\x92\x3\x2");
		sb.Append("\x2\x2\x92\x94\x3\x2\x2\x2\x93\x91\x3\x2\x2\x2\x94\x95\a\x15");
		sb.Append("\x2\x2\x95\t\x3\x2\x2\x2\x96\x98\a\f\x2\x2\x97\x99\a\x1C\x2");
		sb.Append("\x2\x98\x97\x3\x2\x2\x2\x99\x9A\x3\x2\x2\x2\x9A\x98\x3\x2\x2");
		sb.Append("\x2\x9A\x9B\x3\x2\x2\x2\x9B\x9C\x3\x2\x2\x2\x9C\x9E\a\a\x2\x2");
		sb.Append("\x9D\x9F\a\x1C\x2\x2\x9E\x9D\x3\x2\x2\x2\x9F\xA0\x3\x2\x2\x2");
		sb.Append("\xA0\x9E\x3\x2\x2\x2\xA0\xA1\x3\x2\x2\x2\xA1\xA2\x3\x2\x2\x2");
		sb.Append("\xA2\xA4\t\x2\x2\x2\xA3\xA5\a\x1C\x2\x2\xA4\xA3\x3\x2\x2\x2");
		sb.Append("\xA5\xA6\x3\x2\x2\x2\xA6\xA4\x3\x2\x2\x2\xA6\xA7\x3\x2\x2\x2");
		sb.Append("\xA7\xA8\x3\x2\x2\x2\xA8\xA9\a\x1E\x2\x2\xA9\xAA\a\x1A\x2\x2");
		sb.Append("\xAA\xAB\x5\f\a\x2\xAB\xAC\a\x1B\x2\x2\xAC\xB0\a\x14\x2\x2\xAD");
		sb.Append("\xAF\x5\xE\b\x2\xAE\xAD\x3\x2\x2\x2\xAF\xB2\x3\x2\x2\x2\xB0");
		sb.Append("\xAE\x3\x2\x2\x2\xB0\xB1\x3\x2\x2\x2\xB1\xB3\x3\x2\x2\x2\xB2");
		sb.Append("\xB0\x3\x2\x2\x2\xB3\xB4\a\x15\x2\x2\xB4\v\x3\x2\x2\x2\xB5\xB7");
		sb.Append("\a\b\x2\x2\xB6\xB8\a\x1C\x2\x2\xB7\xB6\x3\x2\x2\x2\xB8\xB9\x3");
		sb.Append("\x2\x2\x2\xB9\xB7\x3\x2\x2\x2\xB9\xBA\x3\x2\x2\x2\xBA\xBB\x3");
		sb.Append("\x2\x2\x2\xBB\xBF\a\x1E\x2\x2\xBC\xBE\a\x1C\x2\x2\xBD\xBC\x3");
		sb.Append("\x2\x2\x2\xBE\xC1\x3\x2\x2\x2\xBF\xBD\x3\x2\x2\x2\xBF\xC0\x3");
		sb.Append("\x2\x2\x2\xC0\xC3\x3\x2\x2\x2\xC1\xBF\x3\x2\x2\x2\xC2\xC4\a");
		sb.Append("\x18\x2\x2\xC3\xC2\x3\x2\x2\x2\xC3\xC4\x3\x2\x2\x2\xC4\xC6\x3");
		sb.Append("\x2\x2\x2\xC5\xB5\x3\x2\x2\x2\xC6\xC9\x3\x2\x2\x2\xC7\xC5\x3");
		sb.Append("\x2\x2\x2\xC7\xC8\x3\x2\x2\x2\xC8\r\x3\x2\x2\x2\xC9\xC7\x3\x2");
		sb.Append("\x2\x2\xCA\xCC\a\x5\x2\x2\xCB\xCD\a\x1C\x2\x2\xCC\xCB\x3\x2");
		sb.Append("\x2\x2\xCD\xCE\x3\x2\x2\x2\xCE\xCC\x3\x2\x2\x2\xCE\xCF\x3\x2");
		sb.Append("\x2\x2\xCF\xD0\x3\x2\x2\x2\xD0\xD4\x5\x12\n\x2\xD1\xD3\a\x1C");
		sb.Append("\x2\x2\xD2\xD1\x3\x2\x2\x2\xD3\xD6\x3\x2\x2\x2\xD4\xD2\x3\x2");
		sb.Append("\x2\x2\xD4\xD5\x3\x2\x2\x2\xD5\xD7\x3\x2\x2\x2\xD6\xD4\x3\x2");
		sb.Append("\x2\x2\xD7\xDB\x5\x18\r\x2\xD8\xDA\a\x1C\x2\x2\xD9\xD8\x3\x2");
		sb.Append("\x2\x2\xDA\xDD\x3\x2\x2\x2\xDB\xD9\x3\x2\x2\x2\xDB\xDC\x3\x2");
		sb.Append("\x2\x2\xDC\xDE\x3\x2\x2\x2\xDD\xDB\x3\x2\x2\x2\xDE\xDF\x5\x12");
		sb.Append("\n\x2\xDF\xE0\a\x17\x2\x2\xE0\x17B\x3\x2\x2\x2\xE1\xE2\a\x11");
		sb.Append("\x2\x2\xE2\xEC\a\x1A\x2\x2\xE3\xE4\a\x1E\x2\x2\xE4\xE5\a\x1A");
		sb.Append("\x2\x2\xE5\xE6\a\x1E\x2\x2\xE6\xED\a\x1B\x2\x2\xE7\xED\a\x1E");
		sb.Append("\x2\x2\xE8\xED\x5\x1A\xE\x2\xE9\xEA\a\x1E\x2\x2\xEA\xEB\a\x19");
		sb.Append("\x2\x2\xEB\xED\a\x1E\x2\x2\xEC\xE3\x3\x2\x2\x2\xEC\xE7\x3\x2");
		sb.Append("\x2\x2\xEC\xE8\x3\x2\x2\x2\xEC\xE9\x3\x2\x2\x2\xED\xEE\x3\x2");
		sb.Append("\x2\x2\xEE\xEF\a\x1B\x2\x2\xEF\x17B\a\x17\x2\x2\xF0\xF1\x5\x10");
		sb.Append("\t\x2\xF1\xF2\a\x17\x2\x2\xF2\x17B\x3\x2\x2\x2\xF3\xF5\a\r\x2");
		sb.Append("\x2\xF4\xF6\a\x1C\x2\x2\xF5\xF4\x3\x2\x2\x2\xF6\xF7\x3\x2\x2");
		sb.Append("\x2\xF7\xF5\x3\x2\x2\x2\xF7\xF8\x3\x2\x2\x2\xF8\xF9\x3\x2\x2");
		sb.Append("\x2\xF9\xFA\a\x1A\x2\x2\xFA\xFC\a\b\x2\x2\xFB\xFD\a\x1C\x2\x2");
		sb.Append("\xFC\xFB\x3\x2\x2\x2\xFD\xFE\x3\x2\x2\x2\xFE\xFC\x3\x2\x2\x2");
		sb.Append("\xFE\xFF\x3\x2\x2\x2\xFF\x100\x3\x2\x2\x2\x100\x101\a\x1E\x2");
		sb.Append("\x2\x101\x103\a\x16\x2\x2\x102\x104\a\x1C\x2\x2\x103\x102\x3");
		sb.Append("\x2\x2\x2\x104\x105\x3\x2\x2\x2\x105\x103\x3\x2\x2\x2\x105\x106");
		sb.Append("\x3\x2\x2\x2\x106\x107\x3\x2\x2\x2\x107\x108\a\x1E\x2\x2\x108");
		sb.Append("\x109\a\x1B\x2\x2\x109\x10D\a\x14\x2\x2\x10A\x10C\x5\xE\b\x2");
		sb.Append("\x10B\x10A\x3\x2\x2\x2\x10C\x10F\x3\x2\x2\x2\x10D\x10B\x3\x2");
		sb.Append("\x2\x2\x10D\x10E\x3\x2\x2\x2\x10E\x110\x3\x2\x2\x2\x10F\x10D");
		sb.Append("\x3\x2\x2\x2\x110\x17B\a\x15\x2\x2\x111\x115\a\x10\x2\x2\x112");
		sb.Append("\x114\x5\x1A\xE\x2\x113\x112\x3\x2\x2\x2\x114\x117\x3\x2\x2");
		sb.Append("\x2\x115\x113\x3\x2\x2\x2\x115\x116\x3\x2\x2\x2\x116\x11B\x3");
		sb.Append("\x2\x2\x2\x117\x115\x3\x2\x2\x2\x118\x11A\a\x1E\x2\x2\x119\x118");
		sb.Append("\x3\x2\x2\x2\x11A\x11D\x3\x2\x2\x2\x11B\x119\x3\x2\x2\x2\x11B");
		sb.Append("\x11C\x3\x2\x2\x2\x11C\x17B\x3\x2\x2\x2\x11D\x11B\x3\x2\x2\x2");
		sb.Append("\x11E\x120\a\b\x2\x2\x11F\x121\a\x1C\x2\x2\x120\x11F\x3\x2\x2");
		sb.Append("\x2\x121\x122\x3\x2\x2\x2\x122\x120\x3\x2\x2\x2\x122\x123\x3");
		sb.Append("\x2\x2\x2\x123\x124\x3\x2\x2\x2\x124\x128\a\x1E\x2\x2\x125\x127");
		sb.Append("\a\x1C\x2\x2\x126\x125\x3\x2\x2\x2\x127\x12A\x3\x2\x2\x2\x128");
		sb.Append("\x126\x3\x2\x2\x2\x128\x129\x3\x2\x2\x2\x129\x12B\x3\x2\x2\x2");
		sb.Append("\x12A\x128\x3\x2\x2\x2\x12B\x12F\a\x13\x2\x2\x12C\x12E\a\x1C");
		sb.Append("\x2\x2\x12D\x12C\x3\x2\x2\x2\x12E\x131\x3\x2\x2\x2\x12F\x12D");
		sb.Append("\x3\x2\x2\x2\x12F\x130\x3\x2\x2\x2\x130\x132\x3\x2\x2\x2\x131");
		sb.Append("\x12F\x3\x2\x2\x2\x132\x136\x5\x14\v\x2\x133\x135\a\x1C\x2\x2");
		sb.Append("\x134\x133\x3\x2\x2\x2\x135\x138\x3\x2\x2\x2\x136\x134\x3\x2");
		sb.Append("\x2\x2\x136\x137\x3\x2\x2\x2\x137\x139\x3\x2\x2\x2\x138\x136");
		sb.Append("\x3\x2\x2\x2\x139\x13A\a\x17\x2\x2\x13A\x17B\x3\x2\x2\x2\x13B");
		sb.Append("\x13D\a\b\x2\x2\x13C\x13E\a\x1C\x2\x2\x13D\x13C\x3\x2\x2\x2");
		sb.Append("\x13E\x13F\x3\x2\x2\x2\x13F\x13D\x3\x2\x2\x2\x13F\x140\x3\x2");
		sb.Append("\x2\x2\x140\x142\x3\x2\x2\x2\x141\x13B\x3\x2\x2\x2\x141\x142");
		sb.Append("\x3\x2\x2\x2\x142\x143\x3\x2\x2\x2\x143\x147\a\x1E\x2\x2\x144");
		sb.Append("\x146\a\x1C\x2\x2\x145\x144\x3\x2\x2\x2\x146\x149\x3\x2\x2\x2");
		sb.Append("\x147\x145\x3\x2\x2\x2\x147\x148\x3\x2\x2\x2\x148\x14A\x3\x2");
		sb.Append("\x2\x2\x149\x147\x3\x2\x2\x2\x14A\x14E\a\x13\x2\x2\x14B\x14D");
		sb.Append("\a\x1C\x2\x2\x14C\x14B\x3\x2\x2\x2\x14D\x150\x3\x2\x2\x2\x14E");
		sb.Append("\x14C\x3\x2\x2\x2\x14E\x14F\x3\x2\x2\x2\x14F\x153\x3\x2\x2\x2");
		sb.Append("\x150\x14E\x3\x2\x2\x2\x151\x154\a\x1E\x2\x2\x152\x154\x5\x14");
		sb.Append("\v\x2\x153\x151\x3\x2\x2\x2\x153\x152\x3\x2\x2\x2\x154\x158");
		sb.Append("\x3\x2\x2\x2\x155\x157\a\x1C\x2\x2\x156\x155\x3\x2\x2\x2\x157");
		sb.Append("\x15A\x3\x2\x2\x2\x158\x156\x3\x2\x2\x2\x158\x159\x3\x2\x2\x2");
		sb.Append("\x159\x15B\x3\x2\x2\x2\x15A\x158\x3\x2\x2\x2\x15B\x15F\a\x12");
		sb.Append("\x2\x2\x15C\x15E\a\x1C\x2\x2\x15D\x15C\x3\x2\x2\x2\x15E\x161");
		sb.Append("\x3\x2\x2\x2\x15F\x15D\x3\x2\x2\x2\x15F\x160\x3\x2\x2\x2\x160");
		sb.Append("\x164\x3\x2\x2\x2\x161\x15F\x3\x2\x2\x2\x162\x165\a\x1E\x2\x2");
		sb.Append("\x163\x165\x5\x14\v\x2\x164\x162\x3\x2\x2\x2\x164\x163\x3\x2");
		sb.Append("\x2\x2\x165\x169\x3\x2\x2\x2\x166\x168\a\x1C\x2\x2\x167\x166");
		sb.Append("\x3\x2\x2\x2\x168\x16B\x3\x2\x2\x2\x169\x167\x3\x2\x2\x2\x169");
		sb.Append("\x16A\x3\x2\x2\x2\x16A\x16C\x3\x2\x2\x2\x16B\x169\x3\x2\x2\x2");
		sb.Append("\x16C\x17B\a\x17\x2\x2\x16D\x16E\a\x1E\x2\x2\x16E\x175\a\x1A");
		sb.Append("\x2\x2\x16F\x171\a\x1E\x2\x2\x170\x172\a\x18\x2\x2\x171\x170");
		sb.Append("\x3\x2\x2\x2\x171\x172\x3\x2\x2\x2\x172\x174\x3\x2\x2\x2\x173");
		sb.Append("\x16F\x3\x2\x2\x2\x174\x177\x3\x2\x2\x2\x175\x173\x3\x2\x2\x2");
		sb.Append("\x175\x176\x3\x2\x2\x2\x176\x178\x3\x2\x2\x2\x177\x175\x3\x2");
		sb.Append("\x2\x2\x178\x179\a\x1B\x2\x2\x179\x17B\a\x17\x2\x2\x17A\xCA");
		sb.Append("\x3\x2\x2\x2\x17A\xE1\x3\x2\x2\x2\x17A\xF0\x3\x2\x2\x2\x17A");
		sb.Append("\xF3\x3\x2\x2\x2\x17A\x111\x3\x2\x2\x2\x17A\x11E\x3\x2\x2\x2");
		sb.Append("\x17A\x141\x3\x2\x2\x2\x17A\x16D\x3\x2\x2\x2\x17B\xF\x3\x2\x2");
		sb.Append("\x2\x17C\x17D\a\b\x2\x2\x17D\x17F\a\xF\x2\x2\x17E\x180\a\x1C");
		sb.Append("\x2\x2\x17F\x17E\x3\x2\x2\x2\x180\x181\x3\x2\x2\x2\x181\x17F");
		sb.Append("\x3\x2\x2\x2\x181\x182\x3\x2\x2\x2\x182\x183\x3\x2\x2\x2\x183");
		sb.Append("\x187\a\x1E\x2\x2\x184\x186\a\x1C\x2\x2\x185\x184\x3\x2\x2\x2");
		sb.Append("\x186\x189\x3\x2\x2\x2\x187\x185\x3\x2\x2\x2\x187\x188\x3\x2");
		sb.Append("\x2\x2\x188\x18A\x3\x2\x2\x2\x189\x187\x3\x2\x2\x2\x18A\x18E");
		sb.Append("\a\x13\x2\x2\x18B\x18D\a\x1C\x2\x2\x18C\x18B\x3\x2\x2\x2\x18D");
		sb.Append("\x190\x3\x2\x2\x2\x18E\x18C\x3\x2\x2\x2\x18E\x18F\x3\x2\x2\x2");
		sb.Append("\x18F\x191\x3\x2\x2\x2\x190\x18E\x3\x2\x2\x2\x191\x192\x5\x16");
		sb.Append("\f\x2\x192\x11\x3\x2\x2\x2\x193\x196\a\x1E\x2\x2\x194\x196\x5");
		sb.Append("\x14\v\x2\x195\x193\x3\x2\x2\x2\x195\x194\x3\x2\x2\x2\x196\x13");
		sb.Append("\x3\x2\x2\x2\x197\x198\a\x1D\x2\x2\x198\x199\a\x19\x2\x2\x199");
		sb.Append("\x19A\a\x1D\x2\x2\x19A\x15\x3\x2\x2\x2\x19B\x1A2\a\x14\x2\x2");
		sb.Append("\x19C\x19E\x5\x14\v\x2\x19D\x19F\a\x18\x2\x2\x19E\x19D\x3\x2");
		sb.Append("\x2\x2\x19E\x19F\x3\x2\x2\x2\x19F\x1A1\x3\x2\x2\x2\x1A0\x19C");
		sb.Append("\x3\x2\x2\x2\x1A1\x1A4\x3\x2\x2\x2\x1A2\x1A0\x3\x2\x2\x2\x1A2");
		sb.Append("\x1A3\x3\x2\x2\x2\x1A3\x1A5\x3\x2\x2\x2\x1A4\x1A2\x3\x2\x2\x2");
		sb.Append("\x1A5\x1A6\a\x15\x2\x2\x1A6\x17\x3\x2\x2\x2\x1A7\x1A8\t\x3\x2");
		sb.Append("\x2\x1A8\x19\x3\x2\x2\x2\x1A9\x1D2\a\xE\x2\x2\x1AA\x1AE\a\x1E");
		sb.Append("\x2\x2\x1AB\x1AD\a\x1C\x2\x2\x1AC\x1AB\x3\x2\x2\x2\x1AD\x1B0");
		sb.Append("\x3\x2\x2\x2\x1AE\x1AC\x3\x2\x2\x2\x1AE\x1AF\x3\x2\x2\x2\x1AF");
		sb.Append("\x1B4\x3\x2\x2\x2\x1B0\x1AE\x3\x2\x2\x2\x1B1\x1B3\a\x19\x2\x2");
		sb.Append("\x1B2\x1B1\x3\x2\x2\x2\x1B3\x1B6\x3\x2\x2\x2\x1B4\x1B2\x3\x2");
		sb.Append("\x2\x2\x1B4\x1B5\x3\x2\x2\x2\x1B5\x1BA\x3\x2\x2\x2\x1B6\x1B4");
		sb.Append("\x3\x2\x2\x2\x1B7\x1B9\a\x16\x2\x2\x1B8\x1B7\x3\x2\x2\x2\x1B9");
		sb.Append("\x1BC\x3\x2\x2\x2\x1BA\x1B8\x3\x2\x2\x2\x1BA\x1BB\x3\x2\x2\x2");
		sb.Append("\x1BB\x1C0\x3\x2\x2\x2\x1BC\x1BA\x3\x2\x2\x2\x1BD\x1BF\a\x18");
		sb.Append("\x2\x2\x1BE\x1BD\x3\x2\x2\x2\x1BF\x1C2\x3\x2\x2\x2\x1C0\x1BE");
		sb.Append("\x3\x2\x2\x2\x1C0\x1C1\x3\x2\x2\x2\x1C1\x1C6\x3\x2\x2\x2\x1C2");
		sb.Append("\x1C0\x3\x2\x2\x2\x1C3\x1C5\a\x1C\x2\x2\x1C4\x1C3\x3\x2\x2\x2");
		sb.Append("\x1C5\x1C8\x3\x2\x2\x2\x1C6\x1C4\x3\x2\x2\x2\x1C6\x1C7\x3\x2");
		sb.Append("\x2\x2\x1C7\x1D1\x3\x2\x2\x2\x1C8\x1C6\x3\x2\x2\x2\x1C9\x1CD");
		sb.Append("\a\x1E\x2\x2\x1CA\x1CC\a\x19\x2\x2\x1CB\x1CA\x3\x2\x2\x2\x1CC");
		sb.Append("\x1CF\x3\x2\x2\x2\x1CD\x1CB\x3\x2\x2\x2\x1CD\x1CE\x3\x2\x2\x2");
		sb.Append("\x1CE\x1D1\x3\x2\x2\x2\x1CF\x1CD\x3\x2\x2\x2\x1D0\x1AA\x3\x2");
		sb.Append("\x2\x2\x1D0\x1C9\x3\x2\x2\x2\x1D1\x1D4\x3\x2\x2\x2\x1D2\x1D0");
		sb.Append("\x3\x2\x2\x2\x1D2\x1D3\x3\x2\x2\x2\x1D3\x1D5\x3\x2\x2\x2\x1D4");
		sb.Append("\x1D2\x3\x2\x2\x2\x1D5\x1D6\a\xE\x2\x2\x1D6\x1B\x3\x2\x2\x2");
		sb.Append("\x1D7\x1D8\a\t\x2\x2\x1D8\x1D9\a\xF\x2\x2\x1D9\x1DA\a\x4\x2");
		sb.Append("\x2\x1DA\x1D\x3\x2\x2\x2\x46\"(\x32\x38=?\x43KQTV]\x64imv|\x82");
		sb.Append("\x8B\x91\x9A\xA0\xA6\xB0\xB9\xBF\xC3\xC7\xCE\xD4\xDB\xEC\xF7");
		sb.Append("\xFE\x105\x10D\x115\x11B\x122\x128\x12F\x136\x13F\x141\x147");
		sb.Append("\x14E\x153\x158\x15F\x164\x169\x171\x175\x17A\x181\x187\x18E");
		sb.Append("\x195\x19E\x1A2\x1AE\x1B4\x1BA\x1C0\x1C6\x1CD\x1D0\x1D2");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
